/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

    @Test public void testjavaScriptLinter(){
        Path file = Paths.get("resources/gates.js");
        App.javaScriptLinter(file);
        assertEquals("", outContent.toString());
    }
}
