/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;

public class AppTest {
    private final ByteArrayOutputStream outContent = new ByteArrayOutputStream();

    @Test public void testjavaScriptLinter(){
        File pathName = new File("resources/gates.js");
        App.javaScriptLinter(pathName);
        assertEquals("", outContent.toString());
    }
}
