/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testRollMethod() {
        int number = 4;
        int[] result = Library.roll(number);
        assertEquals(number, result.length);
    }

    @Test public void testRollBetweenOneToSixMethod() {
        int [] result = Library.roll(3);
        for (int number : result) {
            boolean actual = number > 0 && number < 7;
            assertTrue(actual);
        }
    }

    @Test public void testContainsDuplicatesFalseMethod() {
        int[] inputArr = {2,4,5,6,8};
        boolean actual = Library.containsDuplicates(inputArr);
        assertFalse(actual);
    }

    @Test public void testContainsDuplicatesTrueMethod() {
        int[] inputArr = {2,4,5,5,8};
        boolean actual = Library.containsDuplicates(inputArr);
        assertTrue(actual);
    }

    @Test public void testCalculatingAveragesMethod() {
        int[] inputArr = {2,4,5,6,8,3};
        float actual = Library.calculatingAverages(inputArr);
        float expected = (float) 4.6666;
        assertEquals(expected, actual, 0.0001);
    }

    @Test public void testArraysOfArraysMethod() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int actual = Library.arraysOfArrays(weeklyMonthTemperatures);
        int expected = 57;
        assertEquals(expected, actual);
    }

    @Test public void testAnalyzeWeather_checkUniqueTemperatures() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String actual = Library.analyzeWeather(weeklyMonthTemperatures);
        String expected = "\nNever saw temperature: 63\nNever saw temperature: 67\nNever saw temperature: 68\nNever saw temperature: 69";
        assertEquals(expected, actual);
    }

    @Test public void testTally_result() {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = Library.tally(votes);
        String actual = winner + " received the most votes!";
        String expected = "Bush received the most votes!";
        assertEquals(expected, actual);
    }


}
