/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Arrays;

public class Library {

    /*
     * Rolling Dice
     */
    public static int[] roll(int inputNumber) {
        int numberOfSides = 6;
        int[] rollArr = new int[inputNumber];
        for (int i = 0; i < inputNumber; i++) {
            int rollNumber = (int)(Math.random() * numberOfSides) + 1;
            rollArr[i] = rollNumber;
        }
        return rollArr;
    }

    /*
     * Contains Duplicates
     */
    public static boolean containsDuplicates(int[] inputArray) {
        for (int i = 0; i < inputArray.length; i++) {
            for (int j = i + 1; j < inputArray.length; j++) {
                if (inputArray[i] == (inputArray[j])) {
                    return true;
                }
            }
        }
    }


}
