/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Arrays;

public class Library {

    /*
     * Rolling Dice
     */
    public static int[] roll(int inputNumber) {
        int numberOfSides = 6;
        int[] rollArr = new int[inputNumber];
        for (int i = 0; i < inputNumber; i++) {
            int rollNumber = (int)(Math.random() * numberOfSides) + 1;
            rollArr[i] = rollNumber;
        }
        return rollArr;
    }

    /*
     * Contains Duplicates
     */
    public static boolean containsDuplicates(int[] inputArray) {
        for (int i = 0; i < inputArray.length; i++) {
            for (int j = i + 1; j < inputArray.length; j++) {
                if (inputArray[i] == (inputArray[j])) {
                    return true;
                }
            }
        }
        return false;
    }

    /*
     * Calculating Averages
     */
    public static int calculatingAverages(int[] inputArray) {
        int total = 0;
        int avg;
        for (int i = 0; i < inputArray.length; i++) {
            total = total + inputArray[i];
        }
        avg = total/(inputArray.length);
        System.out.println(avg);
        return avg;
    }

    /*
     * Arrays of Arrays
     */
    public static int arraysOfArrays(int[][] doubleArr) {
        int lowest = 100;
        for (int i = 0; i < doubleArr.length; i++) {
            int total = 0;
            int avg;
            for (int j = 0; j < doubleArr[i].length; j++) {
                total = total + doubleArr[i][j];
            }
            avg = total/(doubleArr[i].length);
            if (avg < lowest) {
                lowest = avg;
            }
        }
        return lowest;
    }
}
